#!/usr/bin/env python
import asyncio
from motu_websocket_bridge import server
import argparse

def main():
    parser = argparse.ArgumentParser(
        prog='motu_websocket_bridge',
        description="Run the AVB websocket bridge server"
    )
    parser.add_argument('--avbserver', type=str, help="The url of the MOTU AVB server")
    parser.add_argument('--port', type=int, help="The port to listen on")
    parser.set_defaults(avbserver="http://localhost:8888", port=8889)
    args = parser.parse_args()

    asyncio.run(server.main(args.avbserver, args.port))

if __name__ == '__main__':
    main()
    